trigger-chance: 0.05
warn-before-kick: true

gui-items:
  - STONE
  - IRON_INGOT
  - GOLD_INGOT
  - COAL
  - DIAMOND
  - EMERALD

monitored-blocks:
  - STONE
  - DEEPSLATE
  - IRON_ORE
  - DEEPSLATE_IRON_ORE
  - GOLD_ORE
  - DEEPSLATE_GOLD_ORE
  - COAL_ORE
  - DEEPSLATE_COAL_ORE
  - DIAMOND_ORE
  - DEEPSLATE_DIAMOND_ORE
  - LAPIS_ORE
  - DEEPSLATE_LAPIS_ORE
  - REDSTONE_ORE
  - DEEPSLATE_REDSTONE_ORE
  - EMERALD_ORE
  - DEEPSLATE_EMERALD_ORE

messages:
  correct: "§aDoğru seçimi yaptınız!"
  kick: "§cYanlış seçim yaptınız! AFK kontrolünü geçemediniz."